### ISSUE TITLE
Version 2 Roadmap

### ISSUE THREAD

**Issue by visualcookie** [visualcookie/slim-sentinel-auth#2]
# Information for Version 2

With the next major release of this tiny but handy boilerplate, I'll refactor everything from scratch to build a maintainable and readable structure. You can always check out the current status of the refactor in the `version-2` branch.

## New Features

- [x] ~Add `illuminate/database` to use Eloquent ORM -> Needs testing!~
- [x] ~Add `robmorgan/phinx` for migrations~
- [x] ~Add `zeuxisoo/slim-whoops` for beautiful error messages~
- [ ] Add and implement `cartalyst/sentinel`
- [x] Add views for sign in and sign up
- [ ] Add administration dashboard based on Bootstrap 4
- [ ] Support localization

## Under Consideration

- Multiple template styles
